use std::env;
use std::path::PathBuf;

fn main() {
    let sys_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));

    // Resolve libempyrean location. For local development inside this
    // workspace, default to sibling empyrean-c's build artifacts:
    // - Library: ../target/release/libempyrean.{dylib,so}
    // - Header:  ../include/empyrean.h (regenerated by empyrean-c's build.rs)
    //
    // For published crates / external consumers, set EMPYREAN_LIB_DIR
    // and EMPYREAN_INCLUDE_DIR explicitly.
    let workspace_root = sys_dir.join("..");
    let lib_dir = env::var("EMPYREAN_LIB_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| workspace_root.join("target/release"));
    let include_dir = env::var("EMPYREAN_INCLUDE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| workspace_root.join("include"));

    let header = include_dir.join("empyrean.h");

    println!("cargo:rustc-link-search=native={}", lib_dir.display());
    println!("cargo:rustc-link-lib=dylib=empyrean");
    println!("cargo:rerun-if-env-changed=EMPYREAN_LIB_DIR");
    println!("cargo:rerun-if-env-changed=EMPYREAN_INCLUDE_DIR");
    println!("cargo:rerun-if-changed={}", header.display());

    if !header.exists() {
        panic!(
            "empyrean.h not found at {}. Build the sibling empyrean-c \
             crate first (`cargo build -p empyrean-c --release`) or set \
             EMPYREAN_INCLUDE_DIR.",
            header.display()
        );
    }

    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .allowlist_function("empyrean_.*")
        .allowlist_type("Empyrean.*")
        .allowlist_var("EMPYREAN_.*")
        .derive_default(true)
        .generate()
        .expect("Unable to generate empyrean bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Failed to write bindings.rs");
}
